# Generated by Django 5.1.7 on 2025-03-15 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(editable=False, max_length=50, null=True, unique=True),
        ),
    ]
