# Generated by Django 5.1.7 on 2025-03-15 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_alter_product_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serwis',
            name='address',
        ),
        migrations.RemoveField(
            model_name='serwis',
            name='contact',
        ),
        migrations.AddField(
            model_name='serwis',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='serwis',
            name='country',
            field=models.CharField(default='Polska', max_length=100),
        ),
        migrations.AddField(
            model_name='serwis',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='serwis',
            name='number',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='serwis',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='serwis',
            name='postal_code',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='serwis',
            name='street',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='serwis',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
