# Generated by Django 5.1.7 on 2025-03-15 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0003_remove_serwis_address_remove_serwis_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default='null', on_delete=django.db.models.deletion.PROTECT, related_name='products', to='rentals.category'),
        ),
    ]
